
stages:
  - build
  - deploy

build:
  stage: build
  image: gcr.io/cloud-builders/docker
  script:
    - docker build -t gcr.io/$PROJECT_ID/hello-world .
    - docker push gcr.io/$PROJECT_ID/hello-world

deploy:
  stage: deploy
  image: gcr.io/google.com/cloudsdktool/cloud-sdk
  script:
    - gcloud run deploy hello-world --image gcr.io/$PROJECT_ID/hello-world --region us-central1 --platform managed
